<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
var menus = [

	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"人事信息管理",
                        "menuJump":"列表",
                        "tableName":"renshi"
                    }
                ],
                "menu":"人事信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"用户管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"用户管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"房间管理",
                        "menuJump":"列表",
                        "tableName":"room"
                    }
                ],
                "menu":"房间管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"售水管理",
                        "menuJump":"列表",
                        "tableName":"shuibiao"
                    },{
                        "buttons":[
                            "查看",
                            "新增",
                            "删除"
                        ],
                        "menu":"水表缴费管理",
                        "menuJump":"列表",
                        "tableName":"shuibiaoJiaofei"
                    }
                ],
                "menu":"售水管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"售电管理",
                        "menuJump":"列表",
                        "tableName":"dianbiao"
                    }
					,{
                        "buttons":[
                            "查看",
                            "新增",
                            "删除"
                        ],
                        "menu":"电表缴费管理",
                        "menuJump":"列表",
                        "tableName":"dianbiaoJiaofei"
                    }
                ],
                "menu":"售电管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"车位管理",
                        "menuJump":"列表",
                        "tableName":"chewei"
                    }
                ],
                "menu":"车位管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"服务管理",
                        "menuJump":"列表",
                        "tableName":"fuwu"
                    }
                ],
                "menu":"服务管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"物业费管理",
                        "menuJump":"列表",
                        "tableName":"wuyefei"
                    }
                ],
                "menu":"物业费管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公共环境管理",
                        "menuJump":"列表",
                        "tableName":"gonggonghuanjing"
                    }
                ],
                "menu":"公共环境管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"系统公告管理",
                        "menuJump":"列表",
                        "tableName":"xitonggonggao"
                    }
                ],
                "menu":"系统公告管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"用户管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"用户管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"房间管理",
                        "menuJump":"列表",
                        "tableName":"room"
                    }
                ],
                "menu":"房间管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"售水管理",
                        "menuJump":"列表",
                        "tableName":"shuibiao"
                    },{
                        "buttons":[
                            "查看",
                            "新增",
                            "删除"
                        ],
                        "menu":"水表缴费管理",
                        "menuJump":"列表",
                        "tableName":"shuibiaoJiaofei"
                    }
                ],
                "menu":"售水管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"售电管理",
                        "menuJump":"列表",
                        "tableName":"dianbiao"
                    }
					,{
                        "buttons":[
                            "查看",
                            "新增",
                            "删除"
                        ],
                        "menu":"电表缴费管理",
                        "menuJump":"列表",
                        "tableName":"dianbiaoJiaofei"
                    }
                ],
                "menu":"售电管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"车位管理",
                        "menuJump":"列表",
                        "tableName":"chewei"
                    }
                ],
                "menu":"车位管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"服务管理",
                        "menuJump":"列表",
                        "tableName":"fuwu"
                    }
                ],
                "menu":"服务管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"物业费管理",
                        "menuJump":"列表",
                        "tableName":"wuyefei"
                    }
                ],
                "menu":"物业费管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公共环境管理",
                        "menuJump":"列表",
                        "tableName":"gonggonghuanjing"
                    }
                ],
                "menu":"公共环境管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"系统公告管理",
                        "menuJump":"列表",
                        "tableName":"xitonggonggao"
                    }
                ],
                "menu":"系统公告管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"人事",
        "tableName":"renshi"
    }
	,{
        "backMenu":[
            
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"房间管理",
                        "menuJump":"列表",
                        "tableName":"room"
                    }
                ],
                "menu":"房间管理"
            }
			,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"售水管理",
                        "menuJump":"列表",
                        "tableName":"shuibiao"
                    }
					,{
                        "buttons":[
                            "查看"
                        ],
                        "menu":"水表缴费管理",
                        "menuJump":"列表",
                        "tableName":"shuibiaoJiaofei"
                    }
                ],
                "menu":"售水管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"售电管理",
                        "menuJump":"列表",
                        "tableName":"dianbiao"
                    }
					,{
                        "buttons":[
                            "查看"
                        ],
                        "menu":"电表缴费管理",
                        "menuJump":"列表",
                        "tableName":"dianbiaoJiaofei"
                    }
                ],
                "menu":"售电管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"车位管理",
                        "menuJump":"列表",
                        "tableName":"chewei"
                    }
                ],
                "menu":"车位管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"服务管理",
                        "menuJump":"列表",
                        "tableName":"fuwu"
                    }
                ],
                "menu":"服务管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"物业费管理",
                        "menuJump":"列表",
                        "tableName":"wuyefei"
                    }
                ],
                "menu":"物业费管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"公共环境管理",
                        "menuJump":"列表",
                        "tableName":"gonggonghuanjing"
                    }
                ],
                "menu":"公共环境管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"系统公告管理",
                        "menuJump":"列表",
                        "tableName":"xitonggonggao"
                    }
                ],
                "menu":"系统公告管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"用户",
        "tableName":"yonghu"
    }
];

var hasMessage = '';
